steps:
# Step 1: Install Dependenices + Run Training Code
- name: 'python:3.10'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      pip install -r requirements.txt
      python train.py


options:
   logging: CLOUD_LOGGING_ONLY

