steps:
# Step 1: Install dependencies
- name: 'python:3.10'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      pip install -r requirements.txt

# Step 2: Run training
- name: 'python:3.10'
  entrypoint: 'python'
  args: ['train.py']

# Optional: Upload model to GCS
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'model.pkl', 'gs://credit-card-fraud-gcp/']
